version: "3"
services:
  prometheus:
    image: prom/prometheus:v2.1.0
    ports:
     - "9090:9090"
    volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml


  postgres_exporter:
    image: wrouesnel/postgres_exporter
    ports:
     - "9187:9187"
    environment:
     - DATA_SOURCE_NAME="postgresql://postgres:password@localhost:5432/?sslmode=disable"
