# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 30s

scrape_configs:
- job_name: postgres-exporter
  metrics_path: /metrics
  static_configs:
    - targets:
      - postgres_exporter:9187
